modid = "efhexs"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_efhexs/_export/generated"

[template]
icon = "icon.png"
include = [
    "efhexs",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Scryglass"
author = "miyucomics"
show_landing_text = false

[extra.hexcasting]
_pattern_regex = { "!Raw" = '(?P<is_per_world>register|registerPerWorld)\("(?P<name>[^"]+)"?,\s"(?P<signature>[qweasd]+)",\sHexDir\.(?P<startdir>\w+)' }
_per_world_value = "registerPerWorld"

[textures.override]
"efhexs:microphone" = { texture="efhexs:textures/item/microphone.png" }

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/inits/EfhexsPatterns.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

[_common]
src = "../src"
package = "{src}/main/java/miyucomics/efhexs"
